<footer class="footer">
  <div class="footer-heading">
    <h1>Group</h1>
    <a href="mailto:103322558@student.swin.edu.au">Archer</a>
    <a href="mailto:103619739@student.swin.edu.au">Ben</a>
    <a href="mailto:103972490@student.swin.edu.au">William</a>
    <a href="mailto:103994591@student.swin.edu.au">Callum</a>
    <a href="#mailto:103597767@student.swin.edu.au">Jack</a>
  </div>
  <div class="footer-heading">
    <h1>Contact</h1>
    <a href="mailto:103322558@student.swin.edu.au"
      >103322558@student.swin.edu.au</a
    >
    <a href="mailto:103619739@student.swin.edu.au"
      >103619739@student.swin.edu.au</a
    >
    <a href="mailto:103972490@student.swin.edu.au"
      >103972490@student.swin.edu.au</a
    >
    <a href="mailto:103994591@student.swin.edu.au"
      >103994591@student.swin.edu.au</a
    >
    <a href="mailto:103597767@student.swin.edu.au"
      >103597767@student.swin.edu.au</a
    >
  </div>
  <div class="footer-heading">
    <h1>About</h1>
    <a href="http://www.swinburne.edu.au/">School</a>
    <a
      href="https://www.investopedia.com/articles/investing/012715/5-richest-people-world.asp"
      >Investors</a
    >
    <a href="https://www.entrepreneur.com/article/240492">Blog</a>
    <a href="https://www.facebook.com">Facebook Page</a>
  </div>
  <div class="footer-email-form">
    <h1>Join our newsletter</h1>
    <input
      type="email"
      placeholder="Enter your email address"
      id="footer-email"
    />
    <br />
    <input type="submit" value="Sign Up" id="footer-email-btn" />
  </div>
</footer>
